# SPDX-License-Identifier: MIT-0
---
- name: Ensure ufw is installed and enabled
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true

- name: Set default policy for input
  community.general.ufw:
    direction: incoming
    policy: "{{ ufw_rules.input.default_policy }}"
  when: ufw_rules.input.default_policy != ""

- name: Set default policy for output
  community.general.ufw:
    direction: outgoing
    policy: "{{ ufw_rules.output.default_policy }}"
  when: ufw_rules.output.default_policy != ""

- name: Apply input rules
  loop: "{{ ufw_rules.input.rules }}"
  vars:
    rule: "{{ item }}"
  community.general.ufw:
    rule: allow
    direction: in
    comment: "{{ rule.comment }}"
    proto: "{{ rule.proto | default('tcp') }}"
    src: "{{ rule.src_hosts | join(',') if rule.src_hosts else omit }}"
    dest: "{{ rule.dst_hosts | join(',') if rule.dst_hosts else omit }}"
    src_port: "{{ rule.src_ports | join(',') if rule.src_ports else omit }}"
    port: "{{ rule.dst_ports | join(',') if rule.dst_ports else omit }}"
  when: rule is defined

- name: Apply output rules
  loop: "{{ ufw_rules.output.rules }}"
  vars:
    rule: "{{ item }}"
  community.general.ufw:
    rule: allow
    direction: out
    comment: "{{ rule.comment }}"
    proto: "{{ rule.proto | default('tcp') }}"
    src: "{{ rule.src_hosts | join(',') if rule.src_hosts else omit }}"
    dest: "{{ rule.dst_hosts | join(',') if rule.dst_hosts else omit }}"
    src_port: "{{ rule.src_ports | join(',') if rule.src_ports else omit }}"
    port: "{{ rule.dst_ports | join(',') if rule.dst_ports else omit }}"
  when: rule is defined

- name: Enable ufw
  community.general.ufw:
    state: enabled
