---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "docker.io/debian:stable"
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
verifier:
  name: ansible
